"""initial schema

Revision ID: ca88b0042a6f
Revises: 
Create Date: 2026-05-11 18:58:07.435926+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ca88b0042a6f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_pnl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('n_wins', sa.Integer(), nullable=False),
    sa.Column('n_losses', sa.Integer(), nullable=False),
    sa.Column('gross_pnl_inr', sa.Float(), nullable=False),
    sa.Column('net_pnl_inr', sa.Float(), nullable=False),
    sa.Column('fees_inr', sa.Float(), nullable=False),
    sa.Column('delta_pnl_inr', sa.Float(), nullable=False),
    sa.Column('theta_pnl_inr', sa.Float(), nullable=False),
    sa.Column('avg_r', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_slippage_bps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_date', 'strategy_id', name='uq_daily_pnl_date_strategy')
    )
    with op.batch_alter_table('daily_pnl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_pnl_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_pnl_trading_date'), ['trading_date'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('underlying', sa.String(length=16), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_decisions_strategy_ts', ['strategy_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_ts'), ['ts'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_instruments_underlying'), ['underlying'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_market_snapshots_sym_ts', ['symbol', 'timeframe', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_ts'), ['ts'], unique=False)

    op.create_table('nav_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('nav_inr', sa.Float(), nullable=False),
    sa.Column('peak_nav_inr', sa.Float(), nullable=False),
    sa.Column('drawdown_from_peak_pct', sa.Float(), nullable=False),
    sa.Column('circuit_breaker_tripped', sa.Boolean(), nullable=False),
    sa.CheckConstraint('nav_inr >= 0', name='ck_nav_history_nav_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nav_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_history_trading_date'), ['trading_date'], unique=True)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('intended_symbol', sa.String(length=64), nullable=False),
    sa.Column('intended_expiry', sa.DateTime(), nullable=True),
    sa.Column('intended_strike', sa.Float(), nullable=True),
    sa.Column('intended_lots', sa.Integer(), nullable=False),
    sa.Column('intended_premium_inr', sa.Float(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ts'), ['ts'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('entry_ts', sa.DateTime(), nullable=False),
    sa.Column('exit_ts', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('premium_paid_inr', sa.Float(), nullable=True),
    sa.Column('credit_received_inr', sa.Float(), nullable=True),
    sa.Column('realised_pnl_inr', sa.Float(), nullable=True),
    sa.Column('delta_pnl_inr', sa.Float(), nullable=True),
    sa.Column('theta_pnl_inr', sa.Float(), nullable=True),
    sa.Column('fees_inr', sa.Float(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('entry_iv', sa.Float(), nullable=True),
    sa.Column('exit_iv', sa.Float(), nullable=True),
    sa.Column('peak_pnl_inr', sa.Float(), nullable=True),
    sa.Column('trough_pnl_inr', sa.Float(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_entry_ts'), ['entry_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_underlying'), ['underlying'], unique=False)

    op.create_table('legs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('leg_idx', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_inr', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index('ix_legs_trade_idx', ['trade_id', 'leg_idx'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=32), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('leg_idx', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_exchange_order_id'), ['exchange_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_orders_strategy_ts', ['strategy_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ts'))
        batch_op.drop_index(batch_op.f('ix_orders_trade_id'))
        batch_op.drop_index('ix_orders_strategy_ts')
        batch_op.drop_index(batch_op.f('ix_orders_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_orders_state'))
        batch_op.drop_index(batch_op.f('ix_orders_exchange_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.drop_index('ix_legs_trade_idx')
        batch_op.drop_index(batch_op.f('ix_legs_trade_id'))
        batch_op.drop_index(batch_op.f('ix_legs_strategy_id'))

    op.drop_table('legs')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_underlying'))
        batch_op.drop_index(batch_op.f('ix_trades_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_ts'))

    op.drop_table('trades')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ts'))
        batch_op.drop_index(batch_op.f('ix_signals_strategy_id'))

    op.drop_table('signals')
    with op.batch_alter_table('nav_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nav_history_trading_date'))

    op.drop_table('nav_history')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_symbol'))
        batch_op.drop_index('ix_market_snapshots_sym_ts')

    op.drop_table('market_snapshots')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_underlying'))
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))
        batch_op.drop_index(batch_op.f('ix_instruments_product_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_expiry'))

    op.drop_table('instruments')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_ts'))
        batch_op.drop_index('ix_decisions_strategy_ts')
        batch_op.drop_index(batch_op.f('ix_decisions_strategy_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('daily_pnl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_pnl_trading_date'))
        batch_op.drop_index(batch_op.f('ix_daily_pnl_strategy_id'))

    op.drop_table('daily_pnl')
    # ### end Alembic commands ###
